### ISSUE TITLE
Allow changing assets for non-Steam games.

### ISSUE THREAD

**Issue by doZennn** [SteamGridDB/SGDBoop#1]
Possible implementation:
1. BOP is triggered
2. Scan shortcuts.vdf for games, generate appids
3. Show list of games to user in a drop down
4. Save image once user selects

**Comment by Dragonify** [comment]
I agree. I mainly use SteamGrid because I like to add all my non-steam games into the library but don't want to end up with a dull blank cover. I think this should be implemented soon.

**Comment by mpaterakis** [comment]
This is something that we plan on adding regardless. The problem is the implementation.

doZennn's suggestion will be used as a basis, but don't expect this to be implemented soon as I am already busy with other stuff.

**Comment by mpaterakis** [comment]
This feature has now been added in https://github.com/SteamGridDB/SGDBoop/tag/v1.1.0rc1
Latest commit is https://github.com/SteamGridDB/SGDBoop/commit/38fb12f351f4506244171d8d9884839e0bc439fb

**Comment by brett-owen** [comment]
Would it be possible to extend this feature to support non-steam games on another computer, for steam remote play?

Right now these games show up in your steam library like normal non-steam games, but aren't in the list of non-steam games that SGDBoop can apply assets to.
