### ISSUE TITLE
Animated APNG/WebP Support?

### ISSUE THREAD

**Issue by Dragonify** [SteamGridDB/SGDBoop#10]
It doesn't seem like the boop supports files that isn't png extension. Is it possible to have the boop button use a converted png instead?

**Comment by Dragonify** [comment]
Well I've tried multiple Steam and non-Steam games and assets and none of them have any results. For example this: https://www.steamgriddb.com/hero/26934

**Comment by doZennn** [comment]
Works for me, can you post your system information? OS, Browser, where/how Steam is installed, etc.  
![image](https://user-images.githubusercontent.com/10759579/169023865-3fc79e00-70c2-445a-a9d7-2b2582050880.png)
