### ISSUE TITLE
Add option to boop multiple games

### ISSUE THREAD

**Issue by Jpxe** [SteamGridDB/SGDBoop#13]
Hi and thanks for making this great plugin. I have a feature request; I would like to automatically boop multiple games at the same time. 

## Why: 
I have a huge library and manually selecting each individual game is a lot of work.

## My suggestion:
I would like SGDBoop to **automatically** download and apply images for several games in my collection. This would be similar to how library images are handled in projects such as Plex and Jellyfin. 

## How it could work:
I have couple of different ideas on how this could be implemented:
- SGDBoop could detect (or use a database) what games in a users library doesn't have a Steam vertical cover and replace all of those with the highest scoring one from steamgriddb.com
- The user could make a selection of games and then SGDBoop replaces the images with the highest scoring one from steamgriddb.com. The selection of games could be all Steam games in a collection, all games from list, all games in library, etc.
- SGDBoop could replace the art of all installed Steam games.
- SGDBoop could replace the art of all the Steam games in a users library.

The first option is probably one that I would use the most.

What are your thought and is this something that would be possible to implement?

**Comment by doZennn** [comment]
This is out of scope for SGDBoop which is meant to be small scale and selective. What you are looking for is: https://github.com/boppreh/steamgrid
