### ISSUE TITLE
Missing visual C++ 2015 runtime

### ISSUE THREAD

**Issue by SirBedwyr** [SteamGridDB/SGDBoop#16]
Installing SGDBoop for Windows under Parallels for Macbook M1 Pro that runs Windows 11 ARM, the installation fails due to missing vcruntime140.dll. I downloaded and ran the VC++ 2015 runtime installer and SGDBoop installed correctly. This is pretty unique because of the ARM architecture and the way Parallels implements its own Windows compatibility layer for x86 software, but I thought I'd pass it along just in case. 

There's no automatic install process for the runtime. Is it there and it just fails within Parallels or is it just not there? Is auto install worth having?

**Comment by mpaterakis** [comment]
We don't support Mac or any Apple OS.
