### ISSUE TITLE
Not working at all, is there a debug log somewhere?

### ISSUE THREAD

**Issue by Tenome** [SteamGridDB/SGDBoop#17]
I checked the console while running it and it didn't output anything. Program says it registered successfully, enabled Boop, restarted Steam, no changes. Don't even see the cached copy of the art in the Steam folder. Windows, latest Firefox.

**Comment by mpaterakis** [comment]
There is now a debug log. https://github.com/SteamGridDB/SGDBoop/commit/91eaeaecf1a99317f9c3c6df4db008185de2866e

The file `sgdboop_error.log` is created. This file is placed in the same directory as the executable for Windows and in **/var/log** for linux. Only errors are logged.
