### ISSUE TITLE
Handle cases where Steam game could have multiple appid possibilities.

### ISSUE THREAD

**Issue by doZennn** [SteamGridDB/SGDBoop#18]
Some games can have multiple Steam appids, can probably just assign (symlink?) to every appid reported by the API.  
People who bought games before an appid is retired can still have the older app in their library instead of the new one, assets are usually blank too.

Some examples:
- Arma II [[33900](https://steamdb.info/app/33900/), [33910](https://steamdb.info/app/33910/)]
- Battlefleet Gothic: Armada [[317000](https://steamdb.info/app/317000/), [363680](https://steamdb.info/app/363680/), [450770](https://steamdb.info/app/450770/)]
- Dragon Age II [[47900](https://steamdb.info/app/47900/), [99809](https://steamdb.info/app/99809/), [1238040](https://steamdb.info/app/1238040/)]
- Aion [[29640](https://steamdb.info/app/29640/), [29660](https://steamdb.info/app/29660/), [373680](https://steamdb.info/app/373680/)]

**Comment by mpaterakis** [comment]
This can now be done via 30d634ab7c654609ca42be156b64161856caba59.
