### ISSUE TITLE
Sourcemods specifying "gamelogo 1" result in a crash when booping any non-steam game

### ISSUE THREAD

**Issue by Enbika** [SteamGridDB/SGDBoop#24]
One mod that causes this is [Portal: Still Alive](https://www.moddb.com/mods/portal-still-alive-pc).
Technically this also occurs with any non-string containing `game` but `gamelogo` is the only one of which that is actually recognized by Source.

**Comment by mpaterakis** [comment]
Fixed in https://github.com/SteamGridDB/SGDBoop/commit/7e0b0ca9b4da666af1d18aa873e24625816af568

Thanks a ton for the feedback!
