### ISSUE TITLE
Icons blank / vanish after applying using SGDBoop

### ISSUE THREAD

**Issue by Speedy2662** [SteamGridDB/SGDBoop#26]
Hi, trying to use SGDBoop to apply an icon to a non-steam game, however all it does is just resets the icon to be blank. I tried restarting Steam & my PC and it is still blank. I also tried using both Firefox and Chrome. Running latest version (yesterday's release)

![image](https://user-images.githubusercontent.com/8947452/189549094-fa343e3e-51b3-4838-b93a-4142ff91d76e.png)
![image](https://user-images.githubusercontent.com/8947452/189549097-4e189045-cf2c-4d62-938b-4e961e709739.png)

**Comment by mpaterakis** [comment]
Please post the last lines of your logfile.
The logfile's location can be found by launching SGDBoop normally (outside of steamgriddb.com, either via discovery on steam deck or double click in Windows).

**Comment by Speedy2662** [comment]
> Please post the last lines of your logfile.

```
Sun Sep 11 22:05:02 2022
Could not find ModInstallPath (either in regedit or registry.vdf) [97]
```

**Comment by mpaterakis** [comment]
So the file is downloaded normally, but not rendered in Steam. Does this happen with multiple icons on multiple non-steam games?

**Comment by Speedy2662** [comment]
I tried uninstalling the software and installing it again, this time from my C:/ drive. Now I no longer get the error (or any log file)

 I just tried with another Non-Steam game and it worked. I also tried a Steam game which worked fine as well.

However, [https://www.steamgriddb.com/game/5300613/icons](this) icon refuses to be added.
 It just stays blank!

**Comment by mpaterakis** [comment]
Thanks for the feedback, we'll look into this.
If possible, let me know if the other icons/games work when SGDBoop is registered in a non-C drive (because they should).

I'll mention this just to be certain: Don't forget to run SGDBoop as admin to register its new location when moving the exe.

**Comment by Speedy2662** [comment]
In hindsight, the error was probably from when I was spam-installing the .exe as a last resort and one of them must have been without 'admin'. I'll double check later!

**Comment by Speedy2662** [comment]
It works on the previous drive, like I mentioned the error must have been from when I tried to launch it without admin. It was actually registered fine.

I did find another icon that has the same problem;
https://www.steamgriddb.com/icon/14058

Whereas this one gets applied instantly no without an issue;
https://www.steamgriddb.com/icon/121

**Comment by doZennn** [comment]
This is a Steam/CEF limitation. I've added a workaround on the API side. Should be working now, no update to SGDBoop needed.
