### ISSUE TITLE
Can't run as administrator

### ISSUE THREAD

**Issue by MikuArt** [SteamGridDB/SGDBoop#31]
Hello, 

Im having an issue even if I try to launche it as administrator it's saying to launch as an administrator and Im having this report in the log: Could not create URI protocol. [80]

Im using Windows 11 I tried with Opera, Firefox and Chrome nothing changed.

**Comment by TeriosSonic** [comment]
I happen to have the exact same issue... over a year later, even though this is closed. Is there any solution or reason why this is happening? I really want to use this program, but it's just not working.

**Comment by matata018** [comment]
Same. For ages now. Any solution would be appreciated.
