### ISSUE TITLE
CD into System32 before running reg.exe commands

### ISSUE THREAD

**Issue by doZennn** [SteamGridDB/SGDBoop#32]
Workaround for people with broken PATH environment variable #31

**Comment by doZennn** [comment]
Or just `C:\Windows\System32\reg.exe` cause if the their PATH is messed up then there's a chance `%WINDIR%` is too. Just hope they aren't running Windows on something other than `C:` somehow.

**Comment by dougNetD** [comment]
system drives with letters other than C: will not work with this fix, as a workaround i made a symlink to reg.exe in the absolute path required by the app. you could use %SystemDrive% but then that path environment variable may also be broken for some people : /
