### ISSUE TITLE
Enable Visual Styles

### ISSUE THREAD

**Issue by kran27** [SteamGridDB/SGDBoop#35]
Adding this to the manifest on Windows will make the UI elements look better, I've hacked it in to show the result.
```xml
<dependency>
    <dependentAssembly>
        <assemblyIdentity
            type="win32"
            name="Microsoft.Windows.Common-Controls"
            version="6.0.0.0"
            processorArchitecture="*"
            publicKeyToken="6595b64144ccf1df"
            language="*"
        />
    </dependentAssembly>
</dependency>
```
Before and After:
<p>
<img src="https://user-images.githubusercontent.com/56488228/204506294-e54c6790-c915-40d9-ae49-f85d50cff13a.png"/>
<img src="https://user-images.githubusercontent.com/56488228/204506187-a2363c77-f07b-42ae-8532-290321dab4ce.png"/>
</p>

**Comment by mpaterakis** [comment]
Added in 2237ed24648aca080f38b23879a6dfd26a279b41.
