### ISSUE TITLE
460x215 duplicates

### ISSUE THREAD

**Issue by Arikdefrasia** [SteamGridDB/SGDBoop#38]
When using SGDBoop all other sizes are applied and name correctly, but 460x215 art seems to leave behind a duplicate art with a different name.

As you can see from this Deep Rock Galactic example, there's a leftover 460x215 dimension art that I assume should be deleted upon completion of the asset being named properly, but it's not.  This happens with all games/art with the 460x215 dimensions. Running as administrator yields the same results.
![Screenshot 2022-12-14 131157](https://user-images.githubusercontent.com/44817082/207692261-fe0642da-d52e-486d-abf5-a980489bedd2.png)

**Comment by doZennn** [comment]
The longer name is there to support properly changing the wide capsule in Big Picture Mode. It's actually just a symlink so it wont take up any additional space. We'll remove that once Valve fully replaces the current BPM with the new one.
