### ISSUE TITLE
Steam Deck...Could not find any non-steam apps

### ISSUE THREAD

**Issue by Hraefin** [SteamGridDB/SGDBoop#39]
I have gotten this installed properly.  sgdb://boop/test works fine.
I am trying to install artwork using the "Apply with Boop" button but all I get is

SGDBoop Error <2>
Could not find any non-steam apps

I do have non-steam apps...not sure what to configure to get it to find the proper locations in steam on the Steam Deck.

Any thoughts, suggestions?

Thanks.

**Comment by Tedi1997** [comment]
Solved! The shortcut.vbf file must have been corrupted. Deleting it made everything work

**Comment by doZennn** [comment]
Fixed in [v1.2.8](https://github.com/SteamGridDB/SGDBoop/releases/tag/v1.2.8). If it's still not working, please re-open the issue.
