### ISSUE TITLE
Could not find ModInstallPath (either in regedit or registry.vdf) [97]

### ISSUE THREAD

**Issue by baltimoresports** [SteamGridDB/SGDBoop#41]
I get an non-impacting error message every time I apply an image to steam. This does not seem to actually prevent me from adding an image or have any real negative impact outside being slightly annoying due to having to close out the command prompt window. 

```
ERROR: The system was unable to find the specified registry key or value.
Created logfile in C:\tools\SGDBoop\sgdboop_error.log
```

![image](https://user-images.githubusercontent.com/1420685/208519522-b71188bf-0730-4a1d-9d88-f5daf4362282.png)

When looking at the sgdboop_error.log I see this error repeated several times:

```
Fri Nov 18 06:33:04 2022
Could not find ModInstallPath (either in regedit or registry.vdf) [97]
```

I have replicated this same error on two different systems. 

**System Info**
OS: Windows 11
Browser: Firefox
Version: 1.2.6

**Comment by flobiwankenobi** [comment]
I have exact the same problem. Have you solved it?

**Comment by darkphoenixfox** [comment]
Try running the exe as administrator again. Then try to add another artwork
