### ISSUE TITLE
Boop just doesnt work.

### ISSUE THREAD

**Issue by ardishko** [SteamGridDB/SGDBoop#47]
I installed from source, from the AUR, tried the flatpak but It would not change my background or logos even after restarting steam and pc altogether. If there is a log in the AUR version of this then I'd be happy to post it but as things stand I cannot change my backgrounds, logos, heroes or anything of the sort.

My suspicion is that the program doesnt know where to look since my games arent in ~/Games or some other default steam install location.

**Comment by ardishco-the-great** [comment]
(I have tried the troubleshooting steps provided on the website with no luck)

**Comment by ardishco-the-great** [comment]
I made a softlink to ~/.steam/steam since thats what it searches for but with no luck.

**Comment by ardishko** [comment]
Closing this since it's stale and I was an amateur when I had left this issue. Sorry for the inconvenience.
