### ISSUE TITLE
Could not find any non-Steam apps error

### ISSUE THREAD

**Issue by crispyricepc** [SteamGridDB/SGDBoop#49]
I have non-steam apps installed. I'm using the AUR version of SGDBoop.

![image](https://user-images.githubusercontent.com/16229426/215114822-a3aec4b6-fe38-4f53-85d6-acca3cf836cc.png)

The log gives the following error:

```
Fri Jan 27 14:47:08 2023
Could not find "SourceModInstallPath (either in regedit or registry.vdf) [97]

Fri Jan 27 14:47:08 2023
Could not find "ModInstallPath (either in regedit or registry.vdf) [97]

Fri Jan 27 14:47:16 2023
Could not find any non-Steam apps in the according file. [91]
```

`~/.steam/registry.vdf` does contain "SourceModInstallPath" for reference:

```sh
$ grep -e ModInstallPath ~/.steam/registry.vdf
					"SourceModInstallPath"		"/home/crispyrice/.local/share/Steam/steamapps\\sourcemods
```

**Comment by doZennn** [comment]
Fixed in [v1.2.8](https://github.com/SteamGridDB/SGDBoop/releases/tag/v1.2.8). If it's still not working, please re-open the issue.

**Comment by Doldak** [comment]
not fixed!

**Comment by Gianlucas94** [comment]
Same for me

**Comment by JerryDELUXE** [comment]
I still have this issue. (I'm using the flatpak version btw)

**Comment by potens1** [comment]
If someone encounter the same problem, check you did not installed steam with flatpak, uninstalled it and then switched to distrib's one.
I had to manually delete `~/.var/app/com.valvesoftware.Steam` otherwise it was not working.
Hope it helps !

**Comment by janekmal** [comment]
> If someone encounter the same problem, check you did not installed steam with flatpak, uninstalled it and then switched to distrib's one. I had to manually delete `~/.var/app/com.valvesoftware.Steam` otherwise it was not working. Hope it helps !

For me just deleting `~/.var/app/com.valvesoftware.Steam` worked and I'm using the flatpak version on Linux Mint so that's probably not the issue.
