### ISSUE TITLE
Add a section to the troubleshooting steps.

### ISSUE THREAD

**Issue by TeaJamFA** [SteamGridDB/SGDBoop#51]
I was having an issue on my Linux Desktop where Boop would always say it works on the test but would never actually change the artwork. None of the troubleshooting steps ever did anything for me. After searching through the source code I found that it will not scan for the official repository version of Steam if the folder for the Flatpak version of Steam is still there. I had installed and removed the Flatpak version of steam at some point on this system, however even after uninstalling the Flatpak the folder titled com.valvesoftware.Steam in ~/.var/apps still remained. After removing the folder, Boop worked just as advertised.

I recommend adding a section to the https://www.steamgriddb.com/boop pages Troubleshooting (Assets are not changing) section that discusses this issue. Maybe something along the lines of: 
(Linux) If you are if you are not using the Flatpak version of Steam make sure to move, rename, or delete the folder "~/.var/apps/com.valvesoftware.Steam".

**Comment by TrulySc** [comment]
+1 to this being my solution, flatpak does not remove this directory by default so the information could be very helpful.
