### ISSUE TITLE
Doesn't set images for Lutris created shortcuts

### ISSUE THREAD

**Issue by FanderWasTaken** [SteamGridDB/SGDBoop#52]
Hi there! I'm on Fedora 37, running native Steam and SGDBoop v 1.2.6. (newer versions refuse to open game choosing dialog window). Can anyone tell me how to get a log on this issue?

**Comment by FanderWasTaken** [comment]
Quick update: it works for native Linux games (Minecraft in my case), but not for Wine games

**Comment by doZennn** [comment]
Fixed in [v1.2.8](https://github.com/SteamGridDB/SGDBoop/releases/tag/v1.2.8). If not, please re-open the issue.

**Comment by BongoEADGC6** [comment]
Having a similar issue here. Linux install with Wine based games added as shortcuts into steam
