### ISSUE TITLE
Does not set custom artwork on Windows

### ISSUE THREAD

**Issue by TheSynt4x** [SteamGridDB/SGDBoop#53]
Hello!

I have had some issues with SGDBoop as of recent. It has always worked before and without any issues. I've always been able to just go on the website and boop non-steam games but as of recent it only works for some or doesn't work at all. I honestly have no idea. Checking the grid folder, I can see that a file is being created. Upon further inspection, I've tried regenerating the ID myself which is a crc32 and some offset. I get exactly the same ID as boop does. I save the file as {ID}p.jpg in the grid folder. However, the art work does not show up in Steam grid. Has Steam perhaps changed the way it works or maybe it just doesn't work on Windows? I'm using Windows 10.

**Comment by TheSynt4x** [comment]
Some more information: after updating to 1.2.7 on Windows, Boop has completely stopped working for me. I do not see the non-steam game menu to choose from. Testing Boop on the website shows me the popup that says that Boop is up and running.

**Comment by Gu57avo** [comment]
It has never worked for me, when clicking the boop button, cmd shows up, but the window is blank and nothing happens

**Comment by Lemagex** [comment]
> It has never worked for me, when clicking the boop button, cmd shows up, but the window is blank and nothing happens

After having no issues ever, I now face this issue.

I have tried removing the registry entries manually and deleting boop, reinstalling steam, starting fresh, and 3 browsers (Firefox, Edge, Waterfox) now this happens. I wonder if it's to do with steam's new update?

**Comment by doZennn** [comment]
Fixed in [v1.2.8](https://github.com/SteamGridDB/SGDBoop/releases/tag/v1.2.8). If it's still not working, please re-open the issue.
