### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by valiksheva** [SteamGridDB/SGDBoop#55]
Clicking boop-buttons does not change any artwork. I get the pop-up window for selecting non-steam game, but then nothing happens. Tried restarting Steam, rebooting Windows, different versions of SGDBoop, different browsers (Chrome and Firefox). It just does nothing.

**Comment by iCrazyBlaze** [comment]
I found that adding the games to your favourites list will help: I had some gamepass games that I added via UWPHook.
