### ISSUE TITLE
(Windows Version) Asking for Admin Access when already having it. 

### ISSUE THREAD

**Issue by Lulu-Fluffs** [SteamGridDB/SGDBoop#56]
When I launch SGDB it asks for Admin Access when I already did that when launching. I don't know if this is a me thing but I assume the cause is that I started the app forgetting to give it Admin Access. Although I reinstalled the app multiple times to redo it but it shows the error message when being freshly installed.

**Comment by doZennn** [comment]
I made the error message clearer in [v1.2.8](https://github.com/SteamGridDB/SGDBoop/releases/tag/v1.2.8). You're supposed to just use the site after you registered it
