### ISSUE TITLE
Win10: Steam games list pop-up not popping while test pop-up is.

### ISSUE THREAD

**Issue by Frankaupolis** [SteamGridDB/SGDBoop#62]
Hi, the Steam game list pop-up just suddenly stopped working but the test pop-up is still working. All of this after a Win10 update reboot. Tried the steps in the troubleshooting section. I've tried a newly downloaded SGDBoop, in a different location. Restarted Steam. Put Steam in beta mode.. Rebooted PC.. ..but all this to no avail. 

Any ideas?

Thanks.

**Comment by Frankaupolis** [comment]
Hi, although after both a Steam and Windows update the problem still persists, I've just realised that using the BOOP button for official Steam games does work. So this problem is just for Non-Steam games.

**Comment by doZennn** [comment]
Fixed in [v1.2.8](https://github.com/SteamGridDB/SGDBoop/releases/tag/v1.2.8). If it's still not working, please re-open the issue.
