### ISSUE TITLE
Boop original Steam assets to non-Steam games

### ISSUE THREAD

**Issue by tstephenson888** [SteamGridDB/SGDBoop#9]
I own some of my games on Epic Games Launcher and would really like it if I could add the default Steam grid assets to the entries with SGDBoop like you can with custom assets. It's decently easy to download the original assets for games shared between Steam's and Epic's catalogs, like Frostpunk, Cities Skylines or the Jackbox games (see attached screenshot). But having to apply them one at a time is a bit of a hassle. I feel that some automation to easily push the whole grid/hero/logo/icon set to a game would be very helpful, especially if you have a lot of games on external launchers.
![image](https://user-images.githubusercontent.com/22721076/168717933-9708bd58-0fd1-4095-96df-b929aca46ab3.png)

**Comment by doZennn** [comment]
Implemented in v1.2.0
